[package]
name = "echo"
version = "1.0.0"
description = "Echo desktop application"
authors = ["Sivyor"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "echo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
log = "0.4"
tauri = { version = "2.10.3", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-log = "2"
url = "2"
urlencoding = "2"
