import { APP_DEFAULTS, APP_STRINGS } from "../constants/appConfig.js";
import { createTextOverlay } from "../utils/overlayState.js";

/**
 * @typedef {import("../types/app.js").AppState} AppState
 */

/**
 * @returns {AppState}
 */
export default function createAppStore() {
  return {
    mode: APP_DEFAULTS.mode,
    appView: "preview",
    operatorControlsVisible: false,
    operatorPanelOpen: false,
    galleryPanelOpen: false,
    galleryView: "videos",
    operatorReturnMode: APP_DEFAULTS.mode,
    saveDirectoryHandle: null,
    saveDirectoryPath: "",
    saveDirectoryName: APP_STRINGS.saveFolderDefault,
    activeProjectPath: "",
    isDesktopApp: false,
    isFullscreen: false,
    stream: null,
    settingsCameraEnabled: false,
    recorder: null,
    recordingBlob: null,
    recordingUrl: "",
    recordingFilename: "",
    recordingPath: "",
    recordings: [],
    recordingChunks: [],
    captureReady: false,
    cameraStarting: false,
    captureInProgress: false,
    isRecording: false,
    isSaving: false,
    shutterAnimatingOut: false,
    countdownSeconds: APP_DEFAULTS.countdownSeconds,
    recordingTimeoutSeconds: APP_DEFAULTS.recordingTimeoutSeconds,
    countdownValue: null,
    recordIntervalId: null,
    recordingTimeoutId: null,
    recordStartedAt: 0,
    captureOrientation: APP_DEFAULTS.captureOrientation,
    overlays: APP_DEFAULTS.overlayText
      ? [createTextOverlay({
        text: APP_DEFAULTS.overlayText,
        font: APP_DEFAULTS.overlayFont,
        color: APP_DEFAULTS.overlayColor,
        size: APP_DEFAULTS.overlaySize,
        position: { ...APP_DEFAULTS.overlayTextPosition },
        rotation: APP_DEFAULTS.overlayTextRotation
      })]
      : [],
    activeOverlayId: null,
    activeFrameId: APP_DEFAULTS.activeFrameId,
    activeOverlayTarget: APP_DEFAULTS.activeOverlayTarget,
    showTextColorPalette: APP_DEFAULTS.showTextColorPalette,
    draggingOverlayTarget: null,
    draggingOverlayId: null,
    overlayInteraction: null,
    dragPointerId: null,
    dragStartPointer: null,
    dragSurfaceSize: null,
    dragStartPosition: null,
    dragStartOverlayRect: null,
    dragStartRotation: 0,
    dragStartPointerAngle: null,
    dragRotationCenter: null,
    dragStartOverlayScale: { x: 1, y: 1 },
    overlayText: APP_DEFAULTS.overlayText,
    overlayFont: APP_DEFAULTS.overlayFont,
    overlayColor: APP_DEFAULTS.overlayColor,
    overlaySize: APP_DEFAULTS.overlaySize,
    overlayTextPosition: { ...APP_DEFAULTS.overlayTextPosition },
    overlayTextRotation: APP_DEFAULTS.overlayTextRotation,
    logoDataUrl: APP_DEFAULTS.logoDataUrl,
    logoScale: APP_DEFAULTS.logoScale,
    logoRotation: APP_DEFAULTS.logoRotation,
    logoPosition: { ...APP_DEFAULTS.logoPosition },
    instructionPages: [...APP_DEFAULTS.instructionPages],
    instructionTransitionMs: APP_DEFAULTS.instructionTransitionMs,
    instructionSessionActive: false,
    instructionSessionPhase: "before",
    instructionSessionPageId: "",
    postRecordingDecisionVisible: false,
    slideshowSoundEnabled: APP_DEFAULTS.slideshowSoundEnabled,
    slideshowAudioOutputId: APP_DEFAULTS.slideshowAudioOutputId,
    slideshowFadeDurationMs: APP_DEFAULTS.slideshowFadeDurationMs,
    mainWindowMonitorId: APP_DEFAULTS.mainWindowMonitorId,
    mainWindowFullscreen: APP_DEFAULTS.mainWindowFullscreen,
    slideshowMonitorId: APP_DEFAULTS.slideshowMonitorId,
    slideshowFullscreen: APP_DEFAULTS.slideshowFullscreen,
    videoInputId: APP_DEFAULTS.videoInputId,
    audioInputId: APP_DEFAULTS.audioInputId
  };
}
