/**
 * @typedef {{
 *   cameraStage: HTMLElement,
 *   editorStage: HTMLElement,
 *   cameraPreview: HTMLVideoElement,
 *   resultVideo: HTMLVideoElement,
 *   console: HTMLElement,
 *   operatorAccessTrigger: HTMLButtonElement,
 *   recordControl: HTMLElement,
 *   snapButton: HTMLButtonElement,
 *   snapButtonIcon: HTMLElement,
 *   resultPlayButton: HTMLButtonElement,
 *   resultPlayIcon: HTMLElement,
 *   resultNewButton: HTMLButtonElement,
 *   flashOverlay: HTMLElement,
 *   countdownOverlay: HTMLElement,
 *   recordingTimer: HTMLElement,
 *   errorOverlay: HTMLElement,
 *   emptyCamera: HTMLElement,
 *   operatorPanel: HTMLElement,
 *   operatorDialog: HTMLElement,
 *   operatorDialogHeader: HTMLElement,
 *   operatorDialogResize: HTMLButtonElement,
 *   operatorCloseButton: HTMLButtonElement,
 *   frameTray: HTMLElement,
 *   countdownInput: HTMLInputElement,
 *   countdownMinusButton: HTMLButtonElement,
 *   countdownPlusButton: HTMLButtonElement,
 *   logoUploadButton: HTMLButtonElement,
 *   logoInput: HTMLInputElement,
 *   saveFolderButton: HTMLButtonElement,
 *   saveFolderLabel: HTMLElement,
 *   textInput: HTMLInputElement,
 *   fontSelect: HTMLSelectElement,
 *   cameraFrame: HTMLElement,
 *   cameraText: HTMLElement,
 *   resultFrame: HTMLElement,
 *   resultText: HTMLElement
 * }} DomRefs
 */

export {};
